# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 30 Mar 2018 14:28:01 +0000
*               @ALL          1
*               @user         8
