<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Tue, 10 Apr 2018 03:07:42 +0000
 */

$conf['title'] = 'だれwiki(β版)';
$conf['lang'] = 'ja';
$conf['template'] = 'white';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = '2';
$conf['fnencode'] = 'utf-8';
$conf['tpl']['white']['numberedHeading'] = 1;
$conf['tpl']['IUwiki']['numberedHeading'] = '1';
$conf['tpl']['IUwiki']['footer'] = 'footer';

// end auto-generated content
