<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 02 Apr 2018 09:53:46 +0000
 */

$conf['title'] = 'だれwiki(beta版)';
$conf['lang'] = 'ja';
$conf['template'] = 'IUwiki';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = '2';
$conf['fnencode'] = 'utf-8';
$conf['tpl']['IUwiki']['numberedHeading'] = 1;
$conf['tpl']['IUwiki']['footer'] = 'footer';

// end auto-generated content
