<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Fri, 30 Mar 2018 14:29:44 +0000
 */

$conf['title'] = 'basewiki';
$conf['lang'] = 'ja';
$conf['template'] = 'IUwiki';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
